apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petsclinic-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: Blue
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: PetsClinic API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /vets:
        get:
          summary: List all vets
      /pets:
        get:
          summary: List all registred pets
        post:
          summary: Add new pet
      /customers:
        get:
          summary: List all customers
        post:
          summary: Add a customer
      /visits:
        get:
          summary: List all visits
        post:
          summary: Plan a visit
