apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic-api-gateway
  description: |
    Petclinic API gateway
  links:
    - title: Website
      url: http://http://20.31.1.137/#!/welcome
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: suuus/app-templates-springboot-app-on-AKS
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: API
  owner: Blue
  lifecycle: production
  providesApi:
    - API:default/petclinic-api
