identifier: spring-petclinic-visits-service
title: Petclinic visits service
blueprint: microservice
properties:
  servicename: visits-service
relations:
  mySingleRelation: spring-petclinic-customers-service
  myManyRelation:
    - spring-petclinic-api-gateway
    - spring-petclinic-vets-service
