name: Service Deployment in Pet Clinic

on:
  # Triggers the workflow on push events on the main branch
  workflow_dispatch:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '*.png'
    inputs:
      namespace:
        required: true
        description: "Namespace for deploy"
        type: string
      service:
        required: true
        description: "Service to deploy"
        type: string
      environment:
        required: true
        default: production
        description: "Environment to deploy service to"
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string

env:
  LOCATION: 'westeurope'
  HUB_VNET: 'hub-vnet'
  HUB_RG: 'petclinic-hub-westeurope'
  SPOKE_RG: 'petclinic-spoke-westeurope'
  SPOKE_VNET: 'spoke-vnet'
  FW_PRIVATE_IP: '10.0.0.4'
  ROUTE_TABLE_NAME: 'aks-udr'
  ACR_NAME: 'petclinicaksport'
  CLUSTER_NAME: 'aks-petclinic'
  JUMPBOX_ADMIN_USER: 'aksadmin'
  JUMPBOX_ADMIN_PWD: 'aksadmin123**'
  
jobs:
  deploy-service:
    runs-on: ubuntu-latest
    steps:
     - name: Setup Kubekuttel
       uses: azure/setup-kubectl@v3
       id: install
     - name: azure-resource-login
       uses: Azure/azure-resource-login-action@v1.0.0
       with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
     - name: set AKS context
       uses: Azure/aks-set-context@v3
       with:
        resource-group: '${{ env.SPOKE_RG}}'
        cluster-name: '${{ env.CLUSTER_NAME }}'
       id: login
     - name: checkout repo
       uses: actions/checkout@v2.3.4
     - name: Deploy manifest
       uses: Azure/k8s-deploy@v4.9
       with:
        resource-group: ${{ env.SPOKE_RG }}
        name: ${{ env.CLUSTER_NAME }}
        action: deploy
        private-cluster: true
        strategy: basic
        namespace: ${{ github.event.inputs.namespace }}
        manifests: |
          ${{ github.workspace }}/src/spring-petclinic-cloud/k8s/${{ github.event.inputs.service }}-service-deployment.yaml
